### ISSUE TITLE
school.sqlite - exists in the forked repo, causes error due to pre-existing tables

### ISSUE THREAD

**Issue by benjamin-jacobson** [learn-co-curriculum/dsc-database-admin-101-lab#2]
The file "school.sqlite" - exists in the forked repo (master branch), causes error due to pre-existing tables. Suggest removing to avoid errors. Otherwise, students need to delete it or use another workaround to move through the lab. Thanks!

**Comment by sumedh10** [comment]
Thanks for reporting, this is fixed.
